<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-809396K" failures="1" tests="1" name="coyni_mobile.tests.CustomerProfileTest" time="64.406" errors="0" timestamp="2022-01-25T01:52:25 IST" skipped="0">
  <testcase classname="coyni_mobile.tests.CustomerProfileTest" name="testAddDebitCardWithInvalidData" time="64.406">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at ilabs.mobile.reporting.ExtentTestManager.setFailMessageInReport(ExtentTestManager.java:76)
at ilabs.MobileFramework.MobileFunctions.getElement(MobileFunctions.java:99)
at ilabs.MobileFramework.MobileFunctions.click(MobileFunctions.java:120)
at coyni_mobile.components.AddNewPaymentComponent.clickDebitCard(AddNewPaymentComponent.java:24)
at coyni_mobile.tests.CustomerProfileTest.testAddCardWithInvalidData(CustomerProfileTest.java:918)
at coyni_mobile.tests.CustomerProfileTest.testAddDebitCardWithInvalidData(CustomerProfileTest.java:948)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at ilabs.MobileFramework.TestReader.run(TestReader.java:53)
at ilabs.MobileFramework.Runner.runOneIteration(Runner.java:149)
at ilabs.MobileFramework.Runner.run(Runner.java:61)
at coyni_mobile.runner.TestRunner.main(TestRunner.java:9)
]]>
    </failure>
  </testcase> <!-- testAddDebitCardWithInvalidData -->
  <system-out/>
</testsuite> <!-- coyni_mobile.tests.CustomerProfileTest -->
